// <auto-generated />
using System;
using JobRunner.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobRunner.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251223154201_MoreExternalApiChanges")]
    partial class MoreExternalApiChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("JobRunner.Domain.Entities.ExternalApiSyncResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("JobRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId")
                        .IsUnique();

                    b.ToTable("ExternalApiSyncResults");
                });

            modelBuilder.Entity("JobRunner.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JobRunner.Domain.Entities.JobAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JobRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId");

                    b.ToTable("JobAttempts");
                });

            modelBuilder.Entity("JobRunner.Domain.Entities.JobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextVisibleUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("JobId");

                    b.HasIndex("NextVisibleUtc");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "NextVisibleUtc", "CreatedAtUtc");

                    b.ToTable("JobRuns");
                });

            modelBuilder.Entity("JobRunner.Domain.Entities.ExternalApiSyncResult", b =>
                {
                    b.HasOne("JobRunner.Domain.Entities.JobRun", "JobRun")
                        .WithOne("ExternalApiSyncResult")
                        .HasForeignKey("JobRunner.Domain.Entities.ExternalApiSyncResult", "JobRunId");

                    b.Navigation("JobRun");
                });

            modelBuilder.Entity("JobRunner.Domain.Entities.JobAttempt", b =>
                {
                    b.HasOne("JobRunner.Domain.Entities.JobRun", "JobRun")
                        .WithMany("JobAttempts")
                        .HasForeignKey("JobRunId");

                    b.Navigation("JobRun");
                });

            modelBuilder.Entity("JobRunner.Domain.Entities.JobRun", b =>
                {
                    b.HasOne("JobRunner.Domain.Entities.Job", "Job")
                        .WithMany("JobRuns")
                        .HasForeignKey("JobId");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobRunner.Domain.Entities.Job", b =>
                {
                    b.Navigation("JobRuns");
                });

            modelBuilder.Entity("JobRunner.Domain.Entities.JobRun", b =>
                {
                    b.Navigation("ExternalApiSyncResult");

                    b.Navigation("JobAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
